import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google';

// Configure the Roboto font
const roboto = Roboto({
  weight: ['400', '700'], // Specify weights you want to use
  style: ['normal', 'italic'], // Specify styles if needed
  subsets: ['latin'], // Define subsets
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
